# -*- coding: utf-8 -*-
"""selectionsort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mrcokDO6cqIjJXuF6Myp5CZnwQZL1z6
"""

def selectionsort(arr):
    n= len(arr)
    for i in range (n-1):
        mini=i


        for j in range (i + 1, n ):
            if arr[j] < arr[mini]:
                mini= j

        arr[i],arr[mini]=arr[mini],arr[i]

    return arr


num = [12,18,83,90,54,33]
sortednum= selectionsort(num)
print(sortednum)